- name: Copy over Satellite CA cert and add to trust store
  hosts: all

  vars:
    - install_root_cert_pem: files/satellite.lab.cedricanderson.name.pem

  tasks:
    - name: Make sure the folder exists (Red Hat)
      file:
        path: /etc/pki/ca-trust/source/anchors
        state: directory

    - name: Copy PEM into folder (Red Hat)
      copy:
        src: "{{ install_root_cert_pem }}"
        dest: "/etc/pki/ca-trust/source/anchors/{{ install_root_cert_pem | basename }}"
      register: result

    - name: Update CA Trust (Red Hat)
      command: update-ca-trust
      when: result is changed