- name: Install and start a package and service respectively 
  hosts: all

  tasks:
    - name: Package installation. Note: prefix a package group with at sign!
      yum:
        name: "{{ package_name }}"
        state: latest

    - name: Service enabled and started
      service:
        name: "{{ service_name }}"
        state: started
        enabled: true