---
- name: Enable passwordless sudo for wheel group
  hosts: all

  tasks:
    - name: Edit /etc/sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
