- name: Unregister to Red Hat Subscription Management portal
  hosts: all

  vars_files:
    - vault/variables.yml

  vars:        
    rhsm_username: "{{ vault_rhsm_username }}"
    rhsm_password: "{{ vault_rhsm_password }}"

  collections:
    - redhat_subscription

  tasks:

    - name: Unregister
      redhat_subscription:
        state: absent
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
