- name: Register to Red Hat Subscription Management Portal
  hosts: all

  vars_files:
    - vault/variables.yml

  vars:        
    rhsm_username: "{{ vault_rhsm_username }}"
    rhsm_password: "{{ vault_rhsm_password }}"

  collections:
    - redhat_subscription

  tasks:

    - name: Register
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        force_register: true
        release: 8.6