- name: Create Virtual Machine using Satellite
  hosts: localhost
  connection: local
  
  vars_files:
    - vault/variables.yml

  vars:        
    sat_username: "{{ vault_sat_username }}"
    sat_password: "{{ vault_sat_password }}"
    sat_url: "{{ vault_sat_url }}"
    
  collections:
    - redhat.satellite

  tasks:

    - name: "Create a VM on specific ovirt network"
      redhat.satellite.host:
        username: "{{ sat_username }}"
        password: "{{ sat_password }}"
        server_url: "{{ sat_url }}"
        name: "deleteme.remote.lab.cedricanderson.name"
        organization: "CedricOrganization"
        location: "MainSite/RemoteSite"
        hostgroup: "RemoteRHVNodesRHEL8"
        operatingsystem: "RedHat 8.5"
        lifecycle_environment: "Dev"
        provision_method: "image"
        image: "rhel8-ib-ksh"
        compute_resource: "OvirtEngine"
        build: true
        state: present
        interfaces_attributes:
        - type: "interface"
          compute_attributes:
            name: "nic1"
            network: "isolated-capsule"
            interface: "virtio"
        compute_attributes:
            cluster: "Default"
            start: "1"
            cpus: 2
            memory_mb: 4096
      

