- name: Create Virtual Machine
  hosts: localhost
  connection: local
  serial: 1

  tasks:

    - name: Create Virtual Machine
      ovirt_vm:
        auth: "{{ ovirt_auth }}"
        state: "{{ rhv_vm_state }}"
        name: "{{ rhv_vm_name + '.' + rhv_vm_domain }}"
        template: "{{ rhv_vm_template }}"
        cluster: "{{ rhv_vm_cluster }}"
        cpu_cores: "{{ rhv_vm_cpu_cores }}"
        memory: "{{ rhv_vm_memory }}"
        comment: "{{ rhv_vm_comment }} Tower user-job: {{ tower_user_name }}-{{ tower_job_id }}"
        wait: True
        nics:
          - name: "{{ rhv_vm_nic_name }}"
            profile_name: "{{ rhv_vm_nic_profile }}"

  collections:
    - redhat.rhv