- name: Create Virtual Machine using Satellite
  hosts: localhost
  connection: local
  
  vars_files:
    - vault/variables.yml

  vars:        
    sat_username: "{{ vault_sat_username }}"
    sat_password: "{{ vault_sat_password }}"
    sat_url: "{{ vault_sat_url }}"
    
  collections:
    - redhat.satellite

  tasks:

    - name: "Create a VM on specific ovirt network"
      redhat.satellite.host:
        username: "{{ sat_username }}"
        password: "{{ sat_password }}"
        server_url: "{{ sat_url }}"
        name: "{{ rhv_vm_name }}"
        organization: "{{ sat_org }}"
        location: "{{ sat_location }}"
        hostgroup: "{{ sat_host_group }}"
        provision_method: "image"
        image: "{{ rhv_vm_template }}"
        compute_resource: "{{ sat_compute_resource }}"
        build: true
        state: present
        interfaces_attributes:
        - type: "interface"
          compute_attributes:
            name: "nic1"
            network: "{{ rhv_vm_nic_profile }}"
            interface: "virtio"
        compute_attributes:
            cluster: "Default"
            start: "1"
            cpus: {{ rhv_vm_cpu_cores }}
            memory_mb: {{ rhv_vm_memory }}
      

