- name: Trigger a Sync of a Product on Red Hat Satellite using credentials stored in AAP
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - vars/satellite.yml

  collections:
    - redhat.satellite

  tasks:


  - name: "Sync repository"
    redhat.satellite.repository_sync:
      product: "{{ satellite_product }}"
      server_url: "http://{{ satellite_url }}"
      username: "{{ lookup('env','SATELLITE_USERNAME') }}"
      password: "{{ lookup('env','SATELLITE_PASSWORD') }}"
      organization: "{{ org_id | default('DefaultOrg') }}"
