- name: Trigger a Sync of a Product on Red Hat Satellite using credentials stored in AAP
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - vars/satellite.yml
    - vault/variables.yml
    
  vars:        
    sat_username: "{{ vault_sat_username }}"
    sat_password: "{{ vault_sat_password }}"

  collections:
    - redhat.satellite

  tasks:


  - name: "Sync all repositories associated to product"
    redhat.satellite.repository_sync:
      product: "{{ satellite_product }}"
      server_url: "https://{{ satellite_url }}"
      username: "{{ sat_username }}"
      password: "{{ sat_password }}"
      organization: "{{ org_id | default('CedricOrganization') }}"
