---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:latest'

dependencies:
  system: bindep.txt

additional_build_steps:
  prepend:
    - COPY krb5.conf /etc/krb5.conf
    - COPY krb5.keytab /var/kerberos/krb5/user/0/client.keytab
    - COPY krb5.conf.d /etc/krb5.conf.d
    - COPY krb5.include.d /var/lib/sss/pubconf/krb5.include.d
    - COPY kdc-ca-bundle.pem /var/lib/ipa-client/pki/kdc-ca-bundle.pem
    - COPY ca-bundle.pem /var/lib/ipa-client/pki/ca-bundle.pem
