ARG EE_BASE_IMAGE=quay.io/ansible/ansible-runner:latest
ARG EE_BUILDER_IMAGE=registry.redhat.io/ansible-automation-platform-22/ansible-builder-rhel8:latest

FROM $EE_BASE_IMAGE as galaxy
ARG ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=
USER root

ADD _build /build
WORKDIR /build


FROM $EE_BUILDER_IMAGE as builder
ADD _build/requirements.txt requirements.txt
ADD _build/bindep.txt bindep.txt
RUN ansible-builder introspect --sanitize --user-pip=requirements.txt --user-bindep=bindep.txt --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
RUN assemble

FROM $EE_BASE_IMAGE
USER root
COPY krb5.conf /etc/krb5.conf
COPY krb5.keytab /var/kerberos/krb5/user/0/client.keytab
COPY krb5.conf.d /etc/krb5.conf.d
COPY krb5.include.d /var/lib/sss/pubconf/krb5.include.d
COPY kdc-ca-bundle.pem /var/lib/ipa-client/pki/kdc-ca-bundle.pem
COPY ca-bundle.pem /var/lib/ipa-client/pki/ca-bundle.pem
COPY --from=builder /output/ /output/
RUN /output/install-from-bindep && rm -rf /output/wheels
