---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8:latest'

ansible_config: '/etc/ansible/ansible.cfg'

dependencies:
  galaxy: requirements.yml
