---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'aap-ah.lab.cedricanderson.name/ee-supported-rhel8:latest'
  EE_BUILDER_IMAGE: 'aap-ah.lab.cedricanderson.name/ansible-builder-rhel8:latest'

ansible_config: '/etc/ansible/ansible.cfg'

dependencies:
  galaxy: requirements.yml
